name: specta_apis_scheme
description: A sample command-line application.
version: 0.0.0
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkdev/specta_app.git
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
